# Azure Web App: freebergnodeapp
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    # deploy web app using publish profile credentials
    - uses: azure/appservice-actions/webapp@master
      with:
        app-name: freebergnodeapp
        package: '.'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a94c1fbc04c4b3c94485b892f38af55 }}